-- MySQL Script generated by MySQL Workbench
-- 09/05/17 14:58:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SISAE
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SISAE` ;

-- -----------------------------------------------------
-- Schema SISAE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SISAE` DEFAULT CHARACTER SET utf8 ;
USE `SISAE` ;

-- -----------------------------------------------------
-- Table `SISAE`.`UsuTb01`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`UsuTb01` (
  `VcUsuTb01_Cedula` VARCHAR(20) NOT NULL,
  `VcUsuTb01_Nombre` VARCHAR(20) NOT NULL,
  `VcUsuTb01_Ape1` VARCHAR(20) NOT NULL,
  `VcUsuTb01_Ape2` VARCHAR(20) NOT NULL,
  `VcUsuTb01_Direccion` VARCHAR(100) NOT NULL,
  `CrUsuTb01_Sexo` CHAR(1) NOT NULL,
  `VcUsuTb01_Telefono` VARCHAR(8) NOT NULL,
  `VcUsuTb01_Email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`VcUsuTb01_Cedula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SISAE`.`AdmTb02`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`AdmTb02` (
  `VcAdmTb02_IdAdmin` VARCHAR(20) NOT NULL,
  `VcAdmTb02_Clave` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`VcAdmTb02_IdAdmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SISAE`.`EspecialidadTb16`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`EspecialidadTb16` (
  `VcEspecialidadTb16_IdEspecialidad` VARCHAR(20) NOT NULL,
  `VcEspecialidadTb16_Nombre` VARCHAR(20) NOT NULL,
  `InEspecialidadTb16_Cupo` INT NOT NULL,
  PRIMARY KEY (`VcEspecialidadTb16_IdEspecialidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SISAE`.`EstTb03`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`EstTb03` (
  `VcEstTb03_IdEstudiante` VARCHAR(20) NOT NULL,
  `DtEstTb03_FechaNac` DATE NOT NULL,
  `VcEstTb03_Adecuacion` VARCHAR(20) NOT NULL,
  `VcEstTb03_Estado` VARCHAR(20) NOT NULL,
  `VcEspecialidadTb16_IdEspecialidad` VARCHAR(20) NULL,
  PRIMARY KEY (`VcEstTb03_IdEstudiante`),
  CONSTRAINT `FK_Esp`
    FOREIGN KEY (`VcEspecialidadTb16_IdEspecialidad`)
    REFERENCES `SISAE`.`EspecialidadTb16` (`VcEspecialidadTb16_IdEspecialidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Esp_idx` ON `SISAE`.`EstTb03` (`VcEspecialidadTb16_IdEspecialidad` ASC);


-- -----------------------------------------------------
-- Table `SISAE`.`ProfTb04`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`ProfTb04` (
  `VcProfTb04_IdProfesor` VARCHAR(20) NOT NULL,
  `VcProfTb04_Clave` VARCHAR(20) NOT NULL,
  `DtProfTb04_FechaNac` DATE NOT NULL,
  `VcProfTb04_Estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`VcProfTb04_IdProfesor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SISAE`.`FunTb06`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`FunTb06` (
  `VcFunTb06_IdFuncionario` VARCHAR(20) NOT NULL,
  `VcFunTb06_Clave` VARCHAR(20) NOT NULL,
  `DtFunTb06_FechaNac` DATE NOT NULL,
  `VcFunTb06_Estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`VcFunTb06_IdFuncionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SISAE`.`EncTb05`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`EncTb05` (
  `VcEncTb05_IdEncargado` VARCHAR(20) NOT NULL,
  `VcEncTb05_Clave` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`VcEncTb05_IdEncargado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SISAE`.`EstEncTb07`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`EstEncTb07` (
  `VcEncTb05_IdEncargado` VARCHAR(20) NOT NULL,
  `VcEstTb03_IdEstudiante` VARCHAR(20) NOT NULL,
  CONSTRAINT `FK_Est`
    FOREIGN KEY (`VcEstTb03_IdEstudiante`)
    REFERENCES `SISAE`.`EstTb03` (`VcEstTb03_IdEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Enc`
    FOREIGN KEY (`VcEncTb05_IdEncargado`)
    REFERENCES `SISAE`.`EncTb05` (`VcEncTb05_IdEncargado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Est_idx` ON `SISAE`.`EstEncTb07` (`VcEstTb03_IdEstudiante` ASC);


-- -----------------------------------------------------
-- Table `SISAE`.`AsistColeTb08`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`AsistColeTb08` (
  `VcAsistColeTb08_IdAsistCole` VARCHAR(20) NOT NULL,
  `TmAsistColeTb08_HoraEntrada` TIME NOT NULL,
  `DtAsistColeTb08_FechaEntrada` DATE NOT NULL,
  `TmAsistColeTb08_HoraSalida` TIME NOT NULL,
  `DtAsistColeTb08_FechaSalida` DATE NOT NULL,
  `VcEstTb03_IdEstudiante` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`VcAsistColeTb08_IdAsistCole`),
  CONSTRAINT `FK_Est`
    FOREIGN KEY (`VcEstTb03_IdEstudiante`)
    REFERENCES `SISAE`.`EstTb03` (`VcEstTb03_IdEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Est_idx` ON `SISAE`.`AsistColeTb08` (`VcEstTb03_IdEstudiante` ASC);


-- -----------------------------------------------------
-- Table `SISAE`.`MateriaTb17`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`MateriaTb17` (
  `VcMateriaTb17_IdMateria` VARCHAR(20) NOT NULL,
  `VcMateriaTb17_Nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`VcMateriaTb17_IdMateria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SISAE`.`AsistClaseTb18`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`AsistClaseTb18` (
  `VcAsistClaseTb18_IdAsistClase` VARCHAR(20) NOT NULL,
  `DtAsistClaseTb18_Fecha` DATE NOT NULL,
  `TmAsistClaseTb18_Hora` TIME NOT NULL,
  `VcAsistClaseTb18_Estado` VARCHAR(20) NOT NULL,
  `VcMateriaTb17_IdMateria` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`VcAsistClaseTb18_IdAsistClase`),
  CONSTRAINT `FK_Mat`
    FOREIGN KEY (`VcMateriaTb17_IdMateria`)
    REFERENCES `SISAE`.`MateriaTb17` (`VcMateriaTb17_IdMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Mat_idx` ON `SISAE`.`AsistClaseTb18` (`VcMateriaTb17_IdMateria` ASC);


-- -----------------------------------------------------
-- Table `SISAE`.`RepTb10`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`RepTb10` (
  `VcRepTb10_IdReporte` VARCHAR(20) NOT NULL,
  `DtRepTb10_FechaReporte` DATE NOT NULL,
  `TmRepTb10_HoraReporte` TIME NOT NULL,
  `VcAsistClaseTb18_IdAsistClase` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`VcRepTb10_IdReporte`),
  CONSTRAINT `FK_AsCla`
    FOREIGN KEY (`VcAsistClaseTb18_IdAsistClase`)
    REFERENCES `SISAE`.`AsistClaseTb18` (`VcAsistClaseTb18_IdAsistClase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_AsCla_idx` ON `SISAE`.`RepTb10` (`VcAsistClaseTb18_IdAsistClase` ASC);


-- -----------------------------------------------------
-- Table `SISAE`.`InscMateriaTb11`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`InscMateriaTb11` (
  `VcEstTb03_IdEstudiante` VARCHAR(20) NOT NULL,
  `VcInscMateriaTb17_IdMateria` VARCHAR(20) NOT NULL,
  CONSTRAINT `FK_Est`
    FOREIGN KEY (`VcEstTb03_IdEstudiante`)
    REFERENCES `SISAE`.`EstTb03` (`VcEstTb03_IdEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Mat`
    FOREIGN KEY (`VcInscMateriaTb17_IdMateria`)
    REFERENCES `SISAE`.`MateriaTb17` (`VcMateriaTb17_IdMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Est_idx` ON `SISAE`.`InscMateriaTb11` (`VcEstTb03_IdEstudiante` ASC);

CREATE INDEX `FK_Mat_idx` ON `SISAE`.`InscMateriaTb11` (`VcInscMateriaTb17_IdMateria` ASC);


-- -----------------------------------------------------
-- Table `SISAE`.`BachillerTb14`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`BachillerTb14` (
  `VcBachillerTb14_IdBachiller` VARCHAR(20) NOT NULL,
  `VcBachillerTb14_NombreBachiller` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`VcBachillerTb14_IdBachiller`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SISAE`.`GradoTb13`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`GradoTb13` (
  `VcGradoTb13_IdGrado` VARCHAR(20) NOT NULL,
  `VcGradoTb13_NombreGrado` VARCHAR(20) NOT NULL,
  `VcBachillerTb14_IdBachiller` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`VcGradoTb13_IdGrado`),
  CONSTRAINT `FK_Bac`
    FOREIGN KEY (`VcBachillerTb14_IdBachiller`)
    REFERENCES `SISAE`.`BachillerTb14` (`VcBachillerTb14_IdBachiller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Bac_idx` ON `SISAE`.`GradoTb13` (`VcBachillerTb14_IdBachiller` ASC);


-- -----------------------------------------------------
-- Table `SISAE`.`AsigGradoTb12`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`AsigGradoTb12` (
  `VcGradoTb13_IdGrado` VARCHAR(20) NOT NULL,
  `VcProfTb04_IdProf` VARCHAR(20) NOT NULL,
  CONSTRAINT `FK_Prof`
    FOREIGN KEY (`VcProfTb04_IdProf`)
    REFERENCES `SISAE`.`ProfTb04` (`VcProfTb04_IdProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Gra`
    FOREIGN KEY (`VcGradoTb13_IdGrado`)
    REFERENCES `SISAE`.`GradoTb13` (`VcGradoTb13_IdGrado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Prof_idx` ON `SISAE`.`AsigGradoTb12` (`VcProfTb04_IdProf` ASC);

CREATE INDEX `FK_Gra_idx` ON `SISAE`.`AsigGradoTb12` (`VcGradoTb13_IdGrado` ASC);


-- -----------------------------------------------------
-- Table `SISAE`.`GradoEspTb15`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`GradoEspTb15` (
  `VcGradoEspTb15_IdGrado` VARCHAR(20) NOT NULL,
  `VcEspecialidadTb15_IdEspecialidad` VARCHAR(20) NOT NULL,
  CONSTRAINT `FK_Esp`
    FOREIGN KEY (`VcEspecialidadTb15_IdEspecialidad`)
    REFERENCES `SISAE`.`EspecialidadTb16` (`VcEspecialidadTb16_IdEspecialidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Gra`
    FOREIGN KEY (`VcGradoEspTb15_IdGrado`)
    REFERENCES `SISAE`.`GradoTb13` (`VcGradoTb13_IdGrado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Esp_idx` ON `SISAE`.`GradoEspTb15` (`VcEspecialidadTb15_IdEspecialidad` ASC);

CREATE INDEX `FK_Gra_idx` ON `SISAE`.`GradoEspTb15` (`VcGradoEspTb15_IdGrado` ASC);


-- -----------------------------------------------------
-- Table `SISAE`.`SeccionTb20`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`SeccionTb20` (
  `VcSeccionTb20_IdSeccion` VARCHAR(20) NOT NULL,
  `InSeccionTb20_Cupo` INT NOT NULL,
  PRIMARY KEY (`VcSeccionTb20_IdSeccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SISAE`.`AsigMateriaTb19`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`AsigMateriaTb19` (
  `VProfTb04_IdProf` VARCHAR(20) NOT NULL,
  `VcMateriaTb17_IdMateria` VARCHAR(20) NOT NULL,
  CONSTRAINT `FK_Prof`
    FOREIGN KEY (`VProfTb04_IdProf`)
    REFERENCES `SISAE`.`ProfTb04` (`VcProfTb04_IdProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Mat`
    FOREIGN KEY (`VcMateriaTb17_IdMateria`)
    REFERENCES `SISAE`.`MateriaTb17` (`VcMateriaTb17_IdMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Prof_idx` ON `SISAE`.`AsigMateriaTb19` (`VProfTb04_IdProf` ASC);

CREATE INDEX `FK_Mat_idx` ON `SISAE`.`AsigMateriaTb19` (`VcMateriaTb17_IdMateria` ASC);


-- -----------------------------------------------------
-- Table `SISAE`.`FuncRepTb21`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`FuncRepTb21` (
  `VcFuncTb06_IdFuncionario` VARCHAR(20) NOT NULL,
  `VcRepTb10_IdReporte` VARCHAR(20) NOT NULL,
  CONSTRAINT `FK_Fun`
    FOREIGN KEY (`VcFuncTb06_IdFuncionario`)
    REFERENCES `SISAE`.`FunTb06` (`VcFunTb06_IdFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Rep`
    FOREIGN KEY (`VcRepTb10_IdReporte`)
    REFERENCES `SISAE`.`RepTb10` (`VcRepTb10_IdReporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Fun_idx` ON `SISAE`.`FuncRepTb21` (`VcFuncTb06_IdFuncionario` ASC);

CREATE INDEX `FK_Rep_idx` ON `SISAE`.`FuncRepTb21` (`VcRepTb10_IdReporte` ASC);


-- -----------------------------------------------------
-- Table `SISAE`.`EstRepTb22`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`EstRepTb22` (
  `VcEstTb03_IdEstudiante` VARCHAR(20) NOT NULL,
  `VcRepTb10_IdReporte` VARCHAR(20) NOT NULL,
  CONSTRAINT `FK_Est`
    FOREIGN KEY (`VcEstTb03_IdEstudiante`)
    REFERENCES `SISAE`.`EstTb03` (`VcEstTb03_IdEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Rep`
    FOREIGN KEY (`VcRepTb10_IdReporte`)
    REFERENCES `SISAE`.`RepTb10` (`VcRepTb10_IdReporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Est_idx` ON `SISAE`.`EstRepTb22` (`VcEstTb03_IdEstudiante` ASC);

CREATE INDEX `FK_Rep_idx` ON `SISAE`.`EstRepTb22` (`VcRepTb10_IdReporte` ASC);


-- -----------------------------------------------------
-- Table `SISAE`.`EncRepTb09`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`EncRepTb09` (
  `VcEncTb05_IdEncargado` VARCHAR(20) NOT NULL,
  `VcRepTb10_IdReporte` VARCHAR(20) NOT NULL,
  CONSTRAINT `FK_Enc`
    FOREIGN KEY (`VcEncTb05_IdEncargado`)
    REFERENCES `SISAE`.`EncTb05` (`VcEncTb05_IdEncargado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Rep`
    FOREIGN KEY (`VcRepTb10_IdReporte`)
    REFERENCES `SISAE`.`RepTb10` (`VcRepTb10_IdReporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Enc_idx` ON `SISAE`.`EncRepTb09` (`VcEncTb05_IdEncargado` ASC);

CREATE INDEX `FK_Rep_idx` ON `SISAE`.`EncRepTb09` (`VcRepTb10_IdReporte` ASC);


-- -----------------------------------------------------
-- Table `SISAE`.`AsistEstTb23`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`AsistEstTb23` (
  `VcAsistClaseTb18_IdAsistClase` VARCHAR(20) NOT NULL,
  `VcEstTb03_IdEstudiante` VARCHAR(20) NOT NULL,
  CONSTRAINT `FK_Est`
    FOREIGN KEY (`VcEstTb03_IdEstudiante`)
    REFERENCES `SISAE`.`EstTb03` (`VcEstTb03_IdEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_AsCla`
    FOREIGN KEY (`VcAsistClaseTb18_IdAsistClase`)
    REFERENCES `SISAE`.`AsistClaseTb18` (`VcAsistClaseTb18_IdAsistClase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Est_idx` ON `SISAE`.`AsistEstTb23` (`VcEstTb03_IdEstudiante` ASC);

CREATE INDEX `FK_AsiC_idx` ON `SISAE`.`AsistEstTb23` (`VcAsistClaseTb18_IdAsistClase` ASC);


-- -----------------------------------------------------
-- Table `SISAE`.`ProfRepTb24`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`ProfRepTb24` (
  `VcProfTb04_IdProfesor` VARCHAR(20) NOT NULL,
  `VcRepTb10_IdReporte` VARCHAR(20) NOT NULL,
  CONSTRAINT `FK_Prof`
    FOREIGN KEY (`VcProfTb04_IdProfesor`)
    REFERENCES `SISAE`.`ProfTb04` (`VcProfTb04_IdProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Rep`
    FOREIGN KEY (`VcRepTb10_IdReporte`)
    REFERENCES `SISAE`.`RepTb10` (`VcRepTb10_IdReporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Prof_idx` ON `SISAE`.`ProfRepTb24` (`VcProfTb04_IdProfesor` ASC);

CREATE INDEX `FK_Rep_idx` ON `SISAE`.`ProfRepTb24` (`VcRepTb10_IdReporte` ASC);


-- -----------------------------------------------------
-- Table `SISAE`.`SecGradoTb25`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`SecGradoTb25` (
  `VcGradoTb13_IdGrado` VARCHAR(20) NOT NULL,
  `VcSeccionTb20_IdSeccion` VARCHAR(20) NOT NULL,
  CONSTRAINT `FK_Gra`
    FOREIGN KEY (`VcGradoTb13_IdGrado`)
    REFERENCES `SISAE`.`GradoTb13` (`VcGradoTb13_IdGrado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Sec`
    FOREIGN KEY (`VcSeccionTb20_IdSeccion`)
    REFERENCES `SISAE`.`SeccionTb20` (`VcSeccionTb20_IdSeccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Gra_idx` ON `SISAE`.`SecGradoTb25` (`VcGradoTb13_IdGrado` ASC);

CREATE INDEX `FK_Sec_idx` ON `SISAE`.`SecGradoTb25` (`VcSeccionTb20_IdSeccion` ASC);


-- -----------------------------------------------------
-- Table `SISAE`.`GraEstTb26`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`GraEstTb26` (
  `VcEstTb03_IdEstudiante` VARCHAR(20) NOT NULL,
  `VcGradoTb13_IdGrado` VARCHAR(20) NOT NULL,
  CONSTRAINT `FK_Gra`
    FOREIGN KEY (`VcGradoTb13_IdGrado`)
    REFERENCES `SISAE`.`GradoTb13` (`VcGradoTb13_IdGrado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Est`
    FOREIGN KEY (`VcEstTb03_IdEstudiante`)
    REFERENCES `SISAE`.`EstTb03` (`VcEstTb03_IdEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Gra_idx` ON `SISAE`.`GraEstTb26` (`VcGradoTb13_IdGrado` ASC);

CREATE INDEX `FK_Est_idx` ON `SISAE`.`GraEstTb26` (`VcEstTb03_IdEstudiante` ASC);

-- -----------------------------------------------------
-- Table `SISAE`.`SeccionProfTb27`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`SeccionProfTb27` (
  `VcProfTb04_IdProfesor` VARCHAR(20) NOT NULL,
  `VcProfTb04_IdSeccion` VARCHAR(20) NOT NULL,
  CONSTRAINT `FK_Prof`
    FOREIGN KEY (`VcProfTb04_IdProfesor`)
    REFERENCES `SISAE`.`ProfTb04` (`VcProfTb04_IdProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Sec`
    FOREIGN KEY (`VcProfTb04_IdSeccion`)
    REFERENCES `SISAE`.`SeccionTb20` (`VcSeccionTb20_IdSeccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Prof_idx` ON `SISAE`.`SeccionProfTb27` (`VcProfTb04_IdProfesor` ASC);

CREATE INDEX `FK_Sec_idx` ON `SISAE`.`SeccionProfTb27` (`VcProfTb04_IdSeccion` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
