-- MySQL Script generated by MySQL Workbench
-- 09/05/17 14:58:42
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SISAE
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SISAE` ;

-- -----------------------------------------------------
-- Schema SISAE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SISAE` DEFAULT CHARACTER SET utf8 ;
USE `SISAE` ;

-- -----------------------------------------------------
-- Table `SISAE`.`UsuTb01`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`UsuTb01` (
  `VcUsuTb01_Cedula` VARCHAR(20) NOT NULL,
  `VcUsuTb01_Nombre` VARCHAR(20) NOT NULL,
  `VcUsuTb01_Ape1` VARCHAR(20) NOT NULL,
  `VcUsuTb01_Ape2` VARCHAR(20) NOT NULL,
  `VcUsuTb01_Direccion` VARCHAR(100) NOT NULL,
  `CrUsuTb01_Sexo` CHAR(1) NOT NULL,
  `VcUsuTb01_Telefono` VARCHAR(8) NOT NULL,
  `VcUsuTb01_Email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`VcUsuTb01_Cedula`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SISAE`.`AdmTb02`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`AdmTb02` (
  `VcAdmTb02_IdAdmin` VARCHAR(20) NOT NULL,
  `VcAdmTb02_Clave` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`VcAdmTb02_IdAdmin`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SISAE`.`EstTb03`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`EstTb03` (
  `VcEstTb03_IdEstudiante` VARCHAR(20) NOT NULL,
  `DtEstTb03_FechaNac` DATE NOT NULL,
  `VcEstTb03_Adecuacion` VARCHAR(20) NOT NULL,
  `VcEstTb03_Estado` VARCHAR(20) NOT NULL,
  `VcEspecialidadTb16_IdEspecialidad` VARCHAR(20) NULL,
  PRIMARY KEY (`VcEstTb03_IdEstudiante`),
  CONSTRAINT `FK_Especialidad`
    FOREIGN KEY (`VcEspecialidadTb16_IdEspecialidad`)
    REFERENCES `SISAE`.`EspecialidadTb16` (`VcEspecialidadTb16_IdEspecialidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Especialidad_idx` ON `SISAE`.`EstTb03` (`VcEspecialidadTb16_IdEspecialidad` ASC);

-- -----------------------------------------------------
-- Table `SISAE`.`ProfTb04`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`ProfTb04` (
  `VcProfTb04_IdProfesor` VARCHAR(20) NOT NULL,
  `VcProfTb04_Clave` VARCHAR(20) NOT NULL,
  `DtProfTb04_FechaNac` DATE NOT NULL,
  `VcProfTb04_Estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`VcProfTb04_IdProfesor`))
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `SISAE`.`EncTb05`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`EncTb05` (
  `VcEncTb05_IdEncargado` VARCHAR(20) NOT NULL,
  `VcEncTb05_Clave` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`VcEncTb05_IdEncargado`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SISAE`.`FunTb06`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`FunTb06` (
  `VcFunTb06_IdFuncionario` VARCHAR(20) NOT NULL,
  `VcFunTb06_Clave` VARCHAR(20) NOT NULL,
  `DtFunTb06_FechaNac` DATE NOT NULL,
  `VcFunTb06_Estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`VcFunTb06_IdFuncionario`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SISAE`.`EstEncTb07`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`EstEncTb07` (
  `VcEncTb05_IdEncargado` VARCHAR(20) NOT NULL,
  `VcEstTb03_IdEstudiante` VARCHAR(20) NOT NULL,
  CONSTRAINT `FK_Est`
    FOREIGN KEY (`VcEstTb03_IdEstudiante`)
    REFERENCES `SISAE`.`EstTb03` (`VcEstTb03_IdEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Enc`
    FOREIGN KEY (`VcEncTb05_IdEncargado`)
    REFERENCES `SISAE`.`EncTb05` (`VcEncTb05_IdEncargado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Est_idx` ON `SISAE`.`EstEncTb07` (`VcEstTb03_IdEstudiante` ASC);

-- -----------------------------------------------------
-- Table `SISAE`.`AsistColeTb08`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`AsistColeTb08` (
  `VcAsistColeTb08_IdAsistCole` VARCHAR(20) NOT NULL,
  `TmAsistColeTb08_HoraEntrada` TIME NOT NULL,
  `DtAsistColeTb08_FechaEntrada` DATE NOT NULL,
  `TmAsistColeTb08_HoraSalida` TIME NOT NULL,
  `DtAsistColeTb08_FechaSalida` DATE NOT NULL,
  `VcEstTb03_IdEstudiante` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`VcAsistColeTb08_IdAsistCole`),
  CONSTRAINT `FK_Est_Asis`
    FOREIGN KEY (`VcEstTb03_IdEstudiante`)
    REFERENCES `SISAE`.`EstTb03` (`VcEstTb03_IdEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Est_idx` ON `SISAE`.`AsistColeTb08` (`VcEstTb03_IdEstudiante` ASC);

-- -----------------------------------------------------
-- Table `SISAE`.`EncRepTb09`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`EncRepTb09` (
  `VcEncTb05_IdEncargado` VARCHAR(20) NOT NULL,
  `VcRepTb10_IdReporte` VARCHAR(20) NOT NULL,
  CONSTRAINT `FK_Enc_Rep`
    FOREIGN KEY (`VcEncTb05_IdEncargado`)
    REFERENCES `SISAE`.`EncTb05` (`VcEncTb05_IdEncargado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Id_Rep`
    FOREIGN KEY (`VcRepTb10_IdReporte`)
    REFERENCES `SISAE`.`RepTb10` (`VcRepTb10_IdReporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Enc_Rep_idx` ON `SISAE`.`EncRepTb09` (`VcEncTb05_IdEncargado` ASC);

CREATE INDEX `FK_Id_Rep_idx` ON `SISAE`.`EncRepTb09` (`VcRepTb10_IdReporte` ASC);

-- -----------------------------------------------------
-- Table `SISAE`.`RepTb10`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`RepTb10` (
  `VcRepTb10_IdReporte` VARCHAR(20) NOT NULL,
  `DtRepTb10_FechaReporte` DATE NOT NULL,
  `TmRepTb10_HoraReporte` TIME NOT NULL,
  `VcAsistClaseTb18_IdAsistClase` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`VcRepTb10_IdReporte`),
  CONSTRAINT `FK_AsCla`
    FOREIGN KEY (`VcAsistClaseTb18_IdAsistClase`)
    REFERENCES `SISAE`.`AsistClaseTb18` (`VcAsistClaseTb18_IdAsistClase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_AsCla_idx` ON `SISAE`.`RepTb10` (`VcAsistClaseTb18_IdAsistClase` ASC);

-- -----------------------------------------------------
-- Table `SISAE`.`InscMateriaTb11`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`InscMateriaTb11` (
  `VcEstTb03_IdEstudiante` VARCHAR(20) NOT NULL,
  `VcMateriaTb17_IdMateria` VARCHAR(20) NOT NULL,
  CONSTRAINT `FK_Est_Mat`
    FOREIGN KEY (`VcEstTb03_IdEstudiante`)
    REFERENCES `SISAE`.`EstTb03` (`VcEstTb03_IdEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Id_Mat`
    FOREIGN KEY (`VcMateriaTb17_IdMateria`)
    REFERENCES `SISAE`.`MateriaTb17` (`VcMateriaTb17_IdMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Est_Mat_idx` ON `SISAE`.`InscMateriaTb11` (`VcEstTb03_IdEstudiante` ASC);

CREATE INDEX `FK_Id_Mat_idx` ON `SISAE`.`InscMateriaTb11` (`VcMateriaTb17_IdMateria` ASC);

-- -----------------------------------------------------
-- Table `SISAE`.`AsigGradoTb12`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`AsigGradoTb12` (
  `VcGradoTb13_IdGrado` VARCHAR(20) NOT NULL,
  `VcProfTb04_IdProf` VARCHAR(20) NOT NULL,
  CONSTRAINT `FK_Prof`
    FOREIGN KEY (`VcProfTb04_IdProf`)
    REFERENCES `SISAE`.`ProfTb04` (`VcProfTb04_IdProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Gra`
    FOREIGN KEY (`VcGradoTb13_IdGrado`)
    REFERENCES `SISAE`.`GradoTb13` (`VcGradoTb13_IdGrado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Prof_idx` ON `SISAE`.`AsigGradoTb12` (`VcProfTb04_IdProf` ASC);

CREATE INDEX `FK_Gra_idx` ON `SISAE`.`AsigGradoTb12` (`VcGradoTb13_IdGrado` ASC);

-- -----------------------------------------------------
-- Table `SISAE`.`GradoTb13`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`GradoTb13` (
  `VcGradoTb13_IdGrado` VARCHAR(20) NOT NULL,
  `VcGradoTb13_NombreGrado` VARCHAR(20) NOT NULL,
  `VcBachillerTb14_IdBachiller` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`VcGradoTb13_IdGrado`),
  CONSTRAINT `FK_Bac`
    FOREIGN KEY (`VcBachillerTb14_IdBachiller`)
    REFERENCES `SISAE`.`BachillerTb14` (`VcBachillerTb14_IdBachiller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Bac_idx` ON `SISAE`.`GradoTb13` (`VcBachillerTb14_IdBachiller` ASC);

-- -----------------------------------------------------
-- Table `SISAE`.`BachillerTb14`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`BachillerTb14` (
  `VcBachillerTb14_IdBachiller` VARCHAR(20) NOT NULL,
  `VcBachillerTb14_NombreBachiller` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`VcBachillerTb14_IdBachiller`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SISAE`.`GradoEspTb15`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`GradoEspTb15` (
  `VcGradoTb13_IdGrado` VARCHAR(20) NOT NULL,
  `VcEspecialidadTb16_IdEspecialidad` VARCHAR(20) NOT NULL,
  CONSTRAINT `FK_Esp_Gra`
    FOREIGN KEY (`VcEspecialidadTb16_IdEspecialidad`)
    REFERENCES `SISAE`.`EspecialidadTb16` (`VcEspecialidadTb16_IdEspecialidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Gra_Esp`
    FOREIGN KEY (`VcGradoTb13_IdGrado`)
    REFERENCES `SISAE`.`GradoTb13` (`VcGradoTb13_IdGrado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Esp_Gra_idx` ON `SISAE`.`GradoEspTb15` (`VcEspecialidadTb16_IdEspecialidad` ASC);

CREATE INDEX `FK_Gra_Esp_idx` ON `SISAE`.`GradoEspTb15` (`VcGradoTb13_IdGrado` ASC);

-- -----------------------------------------------------
-- Table `SISAE`.`EspecialidadTb16`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`EspecialidadTb16` (
  `VcEspecialidadTb16_IdEspecialidad` VARCHAR(20) NOT NULL,
  `VcEspecialidadTb16_Nombre` VARCHAR(20) NOT NULL,
  `InEspecialidadTb16_Cupo` INT NOT NULL,
  PRIMARY KEY (`VcEspecialidadTb16_IdEspecialidad`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SISAE`.`MateriaTb17`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`MateriaTb17` (
  `VcMateriaTb17_IdMateria` VARCHAR(20) NOT NULL,
  `VcMateriaTb17_Nombre` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`VcMateriaTb17_IdMateria`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SISAE`.`AsistClaseTb18`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`AsistClaseTb18` (
  `VcAsistClaseTb18_IdAsistClase` VARCHAR(20) NOT NULL,
  `DtAsistClaseTb18_Fecha` DATE NOT NULL,
  `TmAsistClaseTb18_Hora` TIME NOT NULL,
  `VcAsistClaseTb18_Estado` VARCHAR(20) NOT NULL,
  `VcMateriaTb17_IdMateria` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`VcAsistClaseTb18_IdAsistClase`),
  CONSTRAINT `FK_Mat`
    FOREIGN KEY (`VcMateriaTb17_IdMateria`)
    REFERENCES `SISAE`.`MateriaTb17` (`VcMateriaTb17_IdMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Mat_idx` ON `SISAE`.`AsistClaseTb18` (`VcMateriaTb17_IdMateria` ASC);

-- -----------------------------------------------------
-- Table `SISAE`.`AsigMateriaTb19`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`AsigMateriaTb19` (
  `VProfTb04_IdProf` VARCHAR(20) NOT NULL,
  `VcMateriaTb17_IdMateria` VARCHAR(20) NOT NULL,
  CONSTRAINT `FK_Prof_M`
    FOREIGN KEY (`VProfTb04_IdProf`)
    REFERENCES `SISAE`.`ProfTb04` (`VcProfTb04_IdProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Mat_P`
    FOREIGN KEY (`VcMateriaTb17_IdMateria`)
    REFERENCES `SISAE`.`MateriaTb17` (`VcMateriaTb17_IdMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Prof_M_idx` ON `SISAE`.`AsigMateriaTb19` (`VProfTb04_IdProf` ASC);

CREATE INDEX `FK_Mat_P_idx` ON `SISAE`.`AsigMateriaTb19` (`VcMateriaTb17_IdMateria` ASC);

-- -----------------------------------------------------
-- Table `SISAE`.`SeccionTb20`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`SeccionTb20` (
  `VcSeccionTb20_IdSeccion` VARCHAR(20) NOT NULL,
  `InSeccionTb20_Cupo` INT NOT NULL,
  PRIMARY KEY (`VcSeccionTb20_IdSeccion`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SISAE`.`FuncRepTb21`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`FuncRepTb21` (
  `VcFuncTb06_IdFuncionario` VARCHAR(20) NOT NULL,
  `VcRepTb10_IdReporte` VARCHAR(20) NOT NULL,
  CONSTRAINT `FK_Fun`
    FOREIGN KEY (`VcFuncTb06_IdFuncionario`)
    REFERENCES `SISAE`.`FunTb06` (`VcFunTb06_IdFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Rep_Func`
    FOREIGN KEY (`VcRepTb10_IdReporte`)
    REFERENCES `SISAE`.`RepTb10` (`VcRepTb10_IdReporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Fun_idx` ON `SISAE`.`FuncRepTb21` (`VcFuncTb06_IdFuncionario` ASC);

CREATE INDEX `FK_Rep_idx` ON `SISAE`.`FuncRepTb21` (`VcRepTb10_IdReporte` ASC);

-- -----------------------------------------------------
-- Table `SISAE`.`EstRepTb22`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`EstRepTb22` (
  `VcEstTb03_IdEstudiante` VARCHAR(20) NOT NULL,
  `VcRepTb10_IdReporte` VARCHAR(20) NOT NULL,
  CONSTRAINT `FK_Est_R`
    FOREIGN KEY (`VcEstTb03_IdEstudiante`)
    REFERENCES `SISAE`.`EstTb03` (`VcEstTb03_IdEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Rep_E`
    FOREIGN KEY (`VcRepTb10_IdReporte`)
    REFERENCES `SISAE`.`RepTb10` (`VcRepTb10_IdReporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Est_R_idx` ON `SISAE`.`EstRepTb22` (`VcEstTb03_IdEstudiante` ASC);

CREATE INDEX `FK_Rep_E_idx` ON `SISAE`.`EstRepTb22` (`VcRepTb10_IdReporte` ASC);

-- -----------------------------------------------------
-- Table `SISAE`.`AsistEstTb23`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`AsistEstTb23` (
  `VcAsistClaseTb18_IdAsistClase` VARCHAR(20) NOT NULL,
  `VcEstTb03_IdEstudiante` VARCHAR(20) NOT NULL,
  CONSTRAINT `FK_A_Est`
    FOREIGN KEY (`VcEstTb03_IdEstudiante`)
    REFERENCES `SISAE`.`EstTb03` (`VcEstTb03_IdEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_As_Cla`
    FOREIGN KEY (`VcAsistClaseTb18_IdAsistClase`)
    REFERENCES `SISAE`.`AsistClaseTb18` (`VcAsistClaseTb18_IdAsistClase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_A_Est_idx` ON `SISAE`.`AsistEstTb23` (`VcEstTb03_IdEstudiante` ASC);

CREATE INDEX `FK_As_Cla_idx` ON `SISAE`.`AsistEstTb23` (`VcAsistClaseTb18_IdAsistClase` ASC);

-- -----------------------------------------------------
-- Table `SISAE`.`ProfRepTb24`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`ProfRepTb24` (
  `VcProfTb04_IdProfesor` VARCHAR(20) NOT NULL,
  `VcRepTb10_IdReporte` VARCHAR(20) NOT NULL,
  CONSTRAINT `FK_Prof_R`
    FOREIGN KEY (`VcProfTb04_IdProfesor`)
    REFERENCES `SISAE`.`ProfTb04` (`VcProfTb04_IdProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Rep_P`
    FOREIGN KEY (`VcRepTb10_IdReporte`)
    REFERENCES `SISAE`.`RepTb10` (`VcRepTb10_IdReporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Prof_R_idx` ON `SISAE`.`ProfRepTb24` (`VcProfTb04_IdProfesor` ASC);

CREATE INDEX `FK_Rep_P_idx` ON `SISAE`.`ProfRepTb24` (`VcRepTb10_IdReporte` ASC);

-- -----------------------------------------------------
-- Table `SISAE`.`SecGradoTb25`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`SecGradoTb25` (
  `VcGradoTb13_IdGrado` VARCHAR(20) NOT NULL,
  `VcSeccionTb20_IdSeccion` VARCHAR(20) NOT NULL,
  CONSTRAINT `FK_S_Gra`
    FOREIGN KEY (`VcGradoTb13_IdGrado`)
    REFERENCES `SISAE`.`GradoTb13` (`VcGradoTb13_IdGrado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Sec_G`
    FOREIGN KEY (`VcSeccionTb20_IdSeccion`)
    REFERENCES `SISAE`.`SeccionTb20` (`VcSeccionTb20_IdSeccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_S_Gra_idx` ON `SISAE`.`SecGradoTb25` (`VcGradoTb13_IdGrado` ASC);

CREATE INDEX `FK_Sec_G_idx` ON `SISAE`.`SecGradoTb25` (`VcSeccionTb20_IdSeccion` ASC);

-- -----------------------------------------------------
-- Table `SISAE`.`GraEstTb26`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`GraEstTb26` (
  `VcEstTb03_IdEstudiante` VARCHAR(20) NOT NULL,
  `VcGradoTb13_IdGrado` VARCHAR(20) NOT NULL,
  CONSTRAINT `FK_Gra_E`
    FOREIGN KEY (`VcGradoTb13_IdGrado`)
    REFERENCES `SISAE`.`GradoTb13` (`VcGradoTb13_IdGrado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_G_Est`
    FOREIGN KEY (`VcEstTb03_IdEstudiante`)
    REFERENCES `SISAE`.`EstTb03` (`VcEstTb03_IdEstudiante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Gra_E_idx` ON `SISAE`.`GraEstTb26` (`VcGradoTb13_IdGrado` ASC);

CREATE INDEX `FK_G_Est_idx` ON `SISAE`.`GraEstTb26` (`VcEstTb03_IdEstudiante` ASC);

-- -----------------------------------------------------
-- Table `SISAE`.`SeccionProfTb27`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SISAE`.`SeccionProfTb27` (
  `VcProfTb04_IdProfesor` VARCHAR(20) NOT NULL,
  `VcSeccionTb20_IdSeccion` VARCHAR(20) NOT NULL,
  CONSTRAINT `FK_Prof_S`
    FOREIGN KEY (`VcProfTb04_IdProfesor`)
    REFERENCES `SISAE`.`ProfTb04` (`VcProfTb04_IdProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Sec_P`
    FOREIGN KEY (`VcSeccionTb20_IdSeccion`)
    REFERENCES `SISAE`.`SeccionTb20` (`VcSeccionTb20_IdSeccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `FK_Prof_S_idx` ON `SISAE`.`SeccionProfTb27` (`VcProfTb04_IdProfesor` ASC);

CREATE INDEX `FK_Sec_P_idx` ON `SISAE`.`SeccionProfTb27` (`VcSeccionTb20_IdSeccion` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


/**************************************************************************************************************************************************************/
      
    /* EstTb03 */
/* Guardar Estudiante */
delimiter $
create procedure PaEstTb03_GuardarEst (in IdEst varchar(20),  in FecNacEst date, in Adecuacion varchar(20), in Estado varchar(20), in IdEspecialidad varchar(20),
in NomEst varchar(20), in Ape1 varchar(20), in Ape2 varchar(20), in Direccion varchar(20), 
in Sexo char(1), in Telefono varchar(8), in Email varchar(100))
begin
	insert into UsuTb01(VcUsuTb01_Cedula, VcUsuTb01_Nombre, VcUsuTb01_Ape1, VcUsuTb01_Ape2, VcUsuTb01_Direccion, CrUsuTb01_Sexo, VcUsuTb01_Telefono, VcUsuTb01_Email)
    values(IdEst, NomEst, Ape1, Ape2, Direccion, Sexo, Telefono, Email);
     insert into EstTb03 (VcEstTb03_IdEstudiante, DtEstTb03_FechaNac, VcEstTb03_Adecuacion, VcEstTb03_Estado, VcEspecialidadTb16_IdEspecialidad)
    values (IdEst, FecNacEst, Adecuacion, Estado, IdEspecialidad);
end $ 
call PaEstTb03_GuardarEst('503580535','1995/10/12','No','Activo','E01','Derian','Esquivel','Venegas',
'Hojancha','M','60918664','deresquivel@outlook.com')

/* Buscar Estudiante */


/* Actualizar Estudiante */
delimiter $
create procedure PaEstTb03_ActualizarEst(in IdEst varchar(20), in FecNacEst Date, in Adecuacion varchar(20),
in Estado varchar(20),in IdEspecialidad varchar(20),in NomEst varchar(20), 
in Ape1 varchar(20), in Ape2 varchar(20), in Direccion varchar(100), in Sexo char(1), in Telefono varchar(8), in Email varchar(100))
begin
	update usutb01,esttb03
    set usutb01.VcUsuTb01_Nombre = NomEst,
    usutb01.VcUsuTb01_Ape1 = Ape1,usutb01.VcUsuTb01_Ape2 = Ape2,usutb01.VcUsuTb01_Direccion = Direccion,usutb01.CrUsuTb01_Sexo = sexo,
    usutb01.VcUsuTb01_Telefono = Telefono,usutb01.VcUsuTb01_Email = Email,esttb03.DtEstTb03_FechaNac = FecNacEst,esttb03.VcEstTb03_Adecuacion = Adecuacion,
    esttb03.VcEstTb03_Estado = Estado,esttb03.VcEspecialidadTb16_IdEspecialidad = IdEspecialidad
    where esttb03.VcEstTb03_IdEstudiante = IdEst and usutb01.VcUsuTb01_Cedula = IdEst;
end $;
/*call PaEstTb03_ActualizarEst('504070289','1995/10/12','No','Activo','E01','Sofia','Esquivel','Venegas',
'Hojancha','F','60918664','deresquivel@outlook.com') */

/* Listar Estudiante */
delimiter $
CREATE PROCEDURE PaEstTb03_Listar ()
begin
 select UsuTb01.VcUsuTb01_Cedula as 'Cedula', UsuTb01.VcUsuTb01_Nombre  as 'Nombre', UsuTb01.VcUsuTb01_Ape1  as '1° Apellido',
 UsuTb01.VcUsuTb01_Ape2  as '2° Apellido', UsuTb01.VcUsuTb01_Direccion as 'Direccion', UsuTb01.CrUsuTb01_Sexo as 'Genero', 
 UsuTb01.VcUsuTb01_Telefono as 'Telefono', UsuTb01.VcUsuTb01_Email as 'Email', EstTb03.VcEstTb03_IdEstudiante as 'Id Estudiante',
 EstTb03.DtEstTb03_FechaNac as 'Fecha Nac', EstTb03.VcEstTb03_Adecuacion as 'Adecuacion', EstTb03.VcEstTb03_Estado as 'Estado', 
EstTb03.VcEspecialidadTb16_IdEspecialidad as 'Especialidad'
    from UsuTb01, EstTb03
    where EstTb03.VcEstTb03_IdEstudiante = UsuTb01.VcUsuTb01_Cedula
	order by EstTb03.VcEstTb03_IdEstudiante;
end $
/*call PaEstTb03_Listar();*/


/* Eliminar Estudiante */


/* Borrar Estudiante*/
delimiter $
create procedure PaEstTb03_BorrarEst(in IdEst varchar(20))
begin
update esttb03 set VcEstTb03_Estado = 'Inactivo' where VcEstTb03_IdEstudiante = IdEst;
end $
/*call PaEstTb03_BorrarEst('504070289');*/


/**************************************************************************************************************************************************************/
	/* ProfTb04 */
/* Guardar Profesor */
delimiter $
create procedure PaProfTb04_GuardarProf(in IdProf varchar(20),  in FecNacProf date, in Clave varchar(20), in Estado varchar(20),
in NomEst varchar(20), in Ape1 varchar(20), in Ape2 varchar(20), in Direccion varchar(100), 
in Sexo char(1), in Telefono varchar(8), in Email varchar(100))
begin
	insert into UsuTb01(VcUsuTb01_Cedula, VcUsuTb01_Nombre, VcUsuTb01_Ape1, VcUsuTb01_Ape2, VcUsuTb01_Direccion, 
    CrUsuTb01_Sexo, VcUsuTb01_Telefono, VcUsuTb01_Email)
    values(IdProf, NomEst, Ape1, Ape2, Direccion, Sexo, Telefono, Email);
     insert into ProfTb04 (VcProfTb04_IdProfesor, VcProfTb04_Clave, DtProfTb04_FechaNac, VcProfTb04_Estado)
    values (IdProf, Clave, FecNacProf, Estado);
end $ 
call PaProfTb04_GuardarProf('116000070','1990/10/12','1234','Activo','Jose','Lopez','Venegas',
'Hojancha','M','60918664','deresquivel@outlook.com')

/* Determina si es profesor */
delimiter $
create procedure PaUsuProf(in id varchar(20), in cla varchar(20))
begin
	select 
    if(p.VcProfTb04_IdProfesor  = id and p.VcProfTb04_Clave = cla,'Profesor', 'No existe') as Tipo
    from ProfTb04 as p inner join usutb01 as u on p.VcProfTb04_IdProfesor = u.VcUsuTb01_Cedula
  where p.VcProfTb04_IdProfesor = id;
end $
call sisae.PaUsuProf('116000070', '1234');

/* Determina si es funcionario */
delimiter $
create procedure PaUsuFunc(in id varchar(20), in cla varchar(20))
begin
	select 
    if(f.VcFunTb06_IdFuncionario  = id and f.VcFunTb06_Clave = cla,'Funcionario', 'No existe') as Tipo
    from funtb06 as f inner join usutb01 as u on f.VcFunTb06_IdFuncionario = u.VcUsuTb01_Cedula
  where f.VcFunTb06_IdFuncionario = id;
end $
call sisae.PaUsuFunc('503580527', '4567');

/* Determina si es encargado */
delimiter $
create procedure PaUsuEnc(in id varchar(20), in cla varchar(20))
begin
	select 
    if(e.VcEncTb05_IdEncargado  = id and e.VcEncTb05_Clave = cla,'Encargado', 'No existe') as Tipo
    from EncTb05 as e inner join usutb01 as u on e.VcEncTb05_IdEncargado = u.VcUsuTb01_Cedula
  where e.VcEncTb05_IdEncargado = id;
end $
call sisae.PaUsuEnc('402370069', '1234');

/* Determina si es administrador */
delimiter $
create procedure PaUsuAdmin(in id varchar(20), in cla varchar(20))
begin
	select 
    if(admtb02.VcAdmTb02_IdAdmin  = id and admtb02.VcAdmTb02_Clave= cla,'Administrador', 'No existe') as Tipo
    from admtb02 
  where admtb02.VcAdmTb02_IdAdmin = id;
end $
call sisae.PaUsuAdmin('502290162', '3344');

/* Llama procedimientos que identifican tipo de usuario */
use sisae;
delimiter $
create procedure PaValidaUsuario(in idusu varchar(20), in clave varchar(20), out tipo varchar(20))
begin
	call PaUsuEnc(idusu, clave);
	call PaUsuAdmin(idusu, clave);
	call PaUsuProf(idusu, clave);
    call PaUsuFunc(idusu, clave);
end $
call sisae.PaValidaUsuario('503580527', '4567', @tipo);


/* Buscar Profesor */
delimiter $
create procedure PaProfTb04_BuscarProf(in cedula varchar(20))
begin
	select u.VcUsuTb01_Cedula as 'Cedula', u.VcUsuTb01_Nombre as 'Nombre', u.VcUsuTb01_Ape1 as '1° Apellido',
    u.VcUsuTb01_Ape2 as '2° Apellido', u.VcUsuTb01_Direccion as 'Direccion', u.CrUsuTb01_Sexo as 'Sexo',
    u.VcUsuTb01_Telefono as 'Telefono', u.VcUsuTb01_Email as 'Correo electronico',
    p.VcProfTb04_IdProfesor as 'Id Profesor', p.DtProfTb04_FechaNac as 'Fecha de nacimiento',
    p.VcProfTb04_Clave as 'Clave', p.VcProfTb04_Estado as 'Estado'
    from ProfTb04 as p inner join usutb01 as u on p.VcProfTb04_IdProfesor = u.VcUsuTb01_Cedula
  where p.VcProfTb04_IdProfesor = cedula;
end $
/*call PaProfTb04_BuscarProf('116000070');*/

/* Actualizar Profesor */
delimiter $
create procedure PaProfTb04_ActualizarProf(in IdProf varchar(20),  in FecNac Date, in Clave varchar(20),
in Estado varchar(20),in Nom varchar(20), 
in Ape1 varchar(20), in Ape2 varchar(20), in Direccion varchar(100), in Sexo char(1), in Telefono varchar(8), in Email varchar(100))
begin
	update usutb01, ProfTb04
    set usutb01.VcUsuTb01_Nombre = Nom,
    usutb01.VcUsuTb01_Ape1 = Ape1,usutb01.VcUsuTb01_Ape2 = Ape2,usutb01.VcUsuTb01_Direccion = Direccion,usutb01.CrUsuTb01_Sexo = sexo,
    usutb01.VcUsuTb01_Telefono = Telefono,usutb01.VcUsuTb01_Email = Email,
    ProfTb04.VcProfTb04_IdProfesor = IdProf, ProfTb04.VcProfTb04_Clave = Clave,
    ProfTb04.DtProfTb04_FechaNac = FecNac, ProfTb04.VcProfTb04_Estado = Estado
    where ProfTb04.VcProfTb04_IdProfesor = IdProf and usutb01.VcUsuTb01_Cedula = IdProf;
end $;
/*call PaProfTb04_ActualizarProf('116000070','1987/10/12','4567','Activo','Jose','Lopez','Zuñiga',
'Nicoya','M','60918664','jlopez@outlook.com');*/

/* Listar Profesor */
delimiter $
CREATE PROCEDURE PaProfTb04_Listar ()
begin
 select UsuTb01.VcUsuTb01_Cedula as 'Cedula', UsuTb01.VcUsuTb01_Nombre  as 'Nombre', UsuTb01.VcUsuTb01_Ape1  as '1° Apellido',
 UsuTb01.VcUsuTb01_Ape2  as '2° Apellido', UsuTb01.VcUsuTb01_Direccion as 'Direccion', UsuTb01.CrUsuTb01_Sexo as 'Genero', 
 UsuTb01.VcUsuTb01_Telefono as 'Telefono', UsuTb01.VcUsuTb01_Email as 'Email', 
 ProfTb04.VcProfTb04_IdProfesor as 'Id Profesor', ProfTb04.VcProfTb04_Clave as 'Clave', 
 ProfTb04.DtProfTb04_FechaNac as 'Fecha Nac', ProfTb04.VcProfTb04_Estado as 'Estado'
    from UsuTb01, ProfTb04
    where ProfTb04.VcProfTb04_IdProfesor = UsuTb01.VcUsuTb01_Cedula
	order by ProfTb04.VcProfTb04_IdProfesor;
end $
/*call PaProfTb04_Listar();*/


/**************************************************************************************************************************************************************/
		/* EncTb05 */
/* Guardar Encargado */
delimiter $
create procedure PaEncTb05_GuardarEnc(in IdEnc varchar(20), in Clave varchar(20),in NomEnc varchar(20), in Ape1 varchar(20), in Ape2 varchar(20), in Direccion varchar(100), 
in Sexo char(1), in Telefono varchar(8), in Email varchar(100))
begin
	insert into UsuTb01(VcUsuTb01_Cedula, VcUsuTb01_Nombre, VcUsuTb01_Ape1, VcUsuTb01_Ape2, VcUsuTb01_Direccion, CrUsuTb01_Sexo, VcUsuTb01_Telefono, VcUsuTb01_Email)
    values(IdEnc, NomEnc, Ape1, Ape2, Direccion, Sexo, Telefono, Email);
	insert into EncTb05(VcEncTb05_IdEncargado, VcEncTb05_Clave)
    values (IdEnc, Clave);
end $
call PaEncTb05_GuardarEnc('402370069','1234','Fernanda','Herrera','Villalobos','Hojancha','F','62001746',
'nose@gmail.com');

/* Actualizar Encargado */
delimiter $
create procedure PaEncTb05_ActualizarEnc( in IdEnc varchar(20), in Clave varchar(20),in NomEnc varchar(20), 
in Ape1 varchar(20), in Ape2 varchar(20), in Direccion varchar(100), in Sexo char(1), in Telefono varchar(8), in Email varchar(100))
begin
	update enctb05,usutb01
    set enctb05.VcEncTb05_Clave = Clave, usutb01.VcUsuTb01_Nombre = NomEnc, usutb01.VcUsuTb01_Ape1 = Ape1, usutb01.VcusuTb01_Ape2 = Ape2,
    usutb01.VcUsutb01_Direccion = Direccion, usutb01.CrUsuTb01_Sexo = Sexo, usutb01.VcUsuTb01_Telefono = Telefono,
	usutb01.VcUsuTb01_Email = Email
    where enctb05.VcEncTb05_IdEncargado = IdEnc  and IdEnc = usutb01.VcUsuTb01_Cedula;
end $
/*call PaEncTb05_ActualizarEnc('402370069','1233','Fernanda','Gonzalez','Villalobos','Samara','F','62001746',
'fer@gmail.com');*/


/**************************************************************************************************************************************************************/
		/* FunTb06 */
/* Guardar Funcionario */
delimiter $
create procedure PaFunTb06_GuardarFunc(in IdFun varchar(20), in Clave varchar(20), in FechaNac date, in Estado varchar(20),
in NomFun varchar(20), in Ape1 varchar(20), in Ape2 varchar(20), in Direccion varchar(20), 
in Sexo char(1), in Telefono varchar(8), in Email varchar(20))
begin
	insert into UsuTb01(VcUsuTb01_Cedula, VcUsuTb01_Nombre, VcUsuTb01_Ape1, VcUsuTb01_Ape2, VcUsuTb01_Direccion, CrUsuTb01_Sexo, VcUsuTb01_Telefono, VcUsuTb01_Email)
    values(IdFun, NomFun, Ape1, Ape2, Direccion, Sexo, Telefono, Email);
    insert into FunTb06 ( VcFunTb06_IdFuncionario,VcFunTb06_Clave, DtFunTb06_FechaNac, VcFunTb06_Estado)
    values (IdFun, Clave, FechaNac, Estado);
end $
call PaFunTb06_GuardarFunc('50230569','1234','1978/03/06', 'Activo', 'Francisco','Perez','Soto','Samara','M','88674699',
'franc@gmail.com');

/* Actualizar Funcionario */
delimiter $
create procedure PaFunTb06_ActualizarFunc(in IdFun varchar(20), in Clave varchar(20), in FechaNac date, in Estado varchar(20),
in NomFun varchar(20),in Ape1 varchar(20), in Ape2 varchar(20), in Direccion varchar(100),
in Sexo char(1), in Telefono varchar(8), in Email varchar(100))
begin
	update FunTb06,usutb01
    set funtb06.VcFunTb06_Clave = Clave, funtb06.DtFunTb06_FechaNac = FechaNac, FunTb06.VcFunTb06_Estado = Estado,
	usutb01.VcUsuTb01_Nombre = NomFun, usutb01.VcUsuTb01_Ape1 = Ape1, usutb01.VcusuTb01_Ape2 = Ape2,
	usutb01.VcUsutb01_Direccion = Direccion, usutb01.CrUsuTb01_Sexo = Sexo, usutb01.VcUsuTb01_Telefono = Telefono,
	usutb01.VcUsuTb01_Email = Email
	where funtb06.VcFunTb06_IdFuncionario = IdFun and usutb01.VcUsuTb01_Cedula = IdFun;
end $
/*call PaFunTb06_ActualizarFunc('50230569','1212','1976/03/06', 'Activo', 'Francisco','Perez','Soto','Nosara','M','88674699',
'franc@gmail.com');*/

/* Borrar funcionario*/
delimiter $
create procedure PaFunTb06_BorrarFunc(in IdFun varchar(20))
begin
update funtb06
set VcFunTb06_Estado = 'Inactivo' where VcFunTb06_IdFuncionario = IdFun;
end $
/*call PaFunTb06_BorrarFunc('50230569');*/

/**************************************************************************************************************************************************************/
		/* EstEncTb07 */
/* Guardar Estudiante encargado */
delimiter $
create procedure PaEstEncTb07_GuardarEstEnc(in IdEncargado varchar(20), in IdEstudiante varchar(20))
begin
	insert into estenctb07(VcEstTb03_IdEstudiante,VcEncTb05_IdEncargado)
    select e.VcEstTb03_IdEstudiante, o.VcEncTb05_IdEncargado
    from esttb03 as e,enctb05 as o
    where e.VcEstTb03_IdEstudiante = IdEstudiante and o.VcEncTb05_IdEncargado = IdEncargado; 
end $
call PaEstEncTb07_GuardarEstEnc('402370069', '504070289');

/* Buscar Estudiante encargado */
delimiter $
create procedure PaEstEncTb07_BuscarEstEnc_Est(in IdEst varchar(20))
begin
	select u.VcUsuTb01_Cedula as 'Cedula',u.VcUsuTb01_Nombre as 'Nombre',u.VcUsuTb01_Ape1 as '1° Apellido',
    u.VcUsuTb01_Ape2 as '2° Apellido',u.VcUsuTb01_Direccion as 'Direccion',u.CrUsuTb01_Sexo as 'Sexo',
    u.VcUsuTb01_Telefono as 'Telefono',u.VcUsuTb01_Email as 'Correo electronico'
    from usutb01 as u inner join enctb05 as e on u.VcUsuTb01_Cedula = e.VcEncTb05_IdEncargado
    inner join estenctb07 as l on e.VcEncTb05_IdEncargado = l.VcEncTb05_IdEncargado
     where l.VcEstTb03_IdEstudiante = IdEst;
end $
/*call PaEstEncTb07_BuscarEstEnc_Est('504070289');*/

/* Buscar Encargado estudiante */
delimiter $
create procedure PaEstEncTb07_BuscarEstEnc_Enc(in IdEnc varchar(20))
begin
	select u.VcUsuTb01_Cedula as 'Cedula',u.VcUsuTb01_Nombre as 'Nombre',u.VcUsuTb01_Ape1 as '1° Apellido',
    u.VcUsuTb01_Ape2 as '2° Apellido',u.VcUsuTb01_Direccion as 'Direccion',u.CrUsuTb01_Sexo as 'Sexo',
    u.VcUsuTb01_Telefono as 'Telefono',u.VcUsuTb01_Email as 'Correo electronico', e.DtEstTb03_FechaNac as 'Fecha de nacimiento',
    e.VcEstTb03_Adecuacion as 'Adecuacion',e.VcEstTb03_Estado as 'Estado'
    from usutb01 as u inner join esttb03 as e on u.VcUsuTb01_Cedula = e.VcEstTb03_IdEstudiante
    join estenctb07 as p on e.VcEstTb03_IdEstudiante = p.VcEstTb03_IdEstudiante
    where p.VcEncTb05_IdEncargado = IdEnc;
end $
/*call PaEstEncTb07_BuscarEstEnc_Enc('402370069');*/

/**************************************************************************************************************************************************************/
	/* AsistColeTb08*/
/* Guardar Asistencia colegio */
delimiter $
create procedure PaAsistColeTb08_GuardarAsistCole(in IdAsistCole varchar(20), in HoraEntrada time, in FechaEntrada date,
in HoraSalida time, in FechaSalida date, in IdEstudiante varchar(20))
begin
	insert into AsistColeTb08 (VcAsistColeTb08_IdAsistCole, TmAsistColeTb08_HoraEntrada, DtAsistColeTb08_FechaEntrada,
    TmAsistColeTb08_HoraSalida, DtAsistColeTb08_FechaSalida, VcEstTb03_IdEstudiante)
    values (IdAsistCole, HoraEntrada, FechaEntrada, HoraSalida, FechaSalida, IdEstudiante);
end $
call PaAsistColeTb08_GuardarAsistCole('AI01', '8:00', '2016/07/12', '4:00', '2016/07/12', '504070289');

/* Actualizar Asistencia colegio */
delimiter $
create procedure PaAsistColeTb08_ActualizarAsistCole(in IdAsistCole varchar(20), in HoraEntrada time, in FechaEntrada date,
in HoraSalida time, in FechaSalida date, in IdEstudiante varchar(20))
begin
	update AsistColeTb08
    set VcAsistColeTb08_IdAsistCole = IdAsistCole, TmAsistColeTb08_HoraEntrada = HoraEntrada  , DtAsistColeTb08_FechaEntrada = FechaEntrada,
	TmAsistColeTb08_HoraSalida = HoraSalida, DtAsistColeTb08_FechaSalida = FechaSalida, VcEstTb03_IdEstudiante = IdEstudiante
	where VcAsistColeTb08_IdAsistCole = IdAsistCole;
end $
/*call PaAsistColeTb08_ActualizarAsistCole('AI01', '7:00', '2016/08/11', '2:00', '2016/07/12', '504070289');*/

/* Buscar Asistencia colegio */
delimiter $
create procedure PaAsistColeTb08_BuscarAsistCole(in IdAsistCole varchar(20))
begin
	select * from AsistColeTb08
     where VcAsistColeTb08_IdAsistCole = IdAsistCole;
end $
/*call PaAsistColeTb08_BuscarAsistCole('AI01');*/

/* Listar Asistencia colegio */ 
delimiter $
CREATE PROCEDURE PaAsistColeTb08_Listar ()
begin
	select * from AsistColeTb08
	order by VcAsistColeTb08_IdAsistCole;
end $
/*call PaAsistColeTb08_Listar();*/

/* Eliminar Asistencia colegio */
delimiter $
create procedure PaAsistColeTb08_EliminarAsistCole(in IdAsisCole varchar(20))
begin
	delete from AsistColeTb08 where VcAsistColeTb08_IdAsistCole = IdAsisCole;
end $
/*call PaAsistColeTb08_EliminarAsistCole('AI01');*/

/**************************************************************************************************************************************************************/
 	/* GradoTb13 */
/* Guardar Grado */
delimiter $
create procedure PaGradoTb13_GuardarGrado(in IdGrado varchar(20), in NombreGrado varchar(20), in IdBachiller varchar(20))
begin
	insert into GradoTb13(VcGradoTb13_IdGrado, VcGradoTb13_NombreGrado, VcBachillerTb14_IdBachiller)
    values (IdGrado, NombreGrado, IdBachiller);
end $
call sisae.PaGradoTb13_GuardarGrado('11', 'Undecimo', '11');

/* Buscar Grado */
delimiter $
create procedure PaGradoTb13_BuscarGrado(in IdGrado varchar(20))
begin
	select * from GradoTb13
     where VcGradoTb13_IdGrado = IdGrado;
end $
/*call sisae.PaGradoTb13_BuscarGrado('11');*/

/* Listar Grado */
delimiter $
CREATE PROCEDURE PaGradoTb13_Listar()
begin
	select * from GradoTb13
	order by VcGradoTb13_IdGrado;
end $  
/*call sisae.PaGradoTb13_Listar();*/

/* Actualizar Grado */
delimiter $
create procedure PaGradoTb13_ActualizarGrado(in IdGrado varchar(20), in NombreGrado varchar(20), in IdBachiller varchar(20))
begin
	update GradoTb13
    set   VcGradoTb13_NombreGrado = NombreGrado, VcBachillerTb14_IdBachiller = IdBachiller 
    where VcGradoTb13_IdGrado = IdGrado;
end $
/*call sisae.PaGradoTb13_ActualizarGrado('11', 'Quinto', '11');*/

/**************************************************************************************************************************************************************/
	/* BachillerTb14 */
/* Guardar Bachiller */
delimiter $
create procedure PaBachillerTb14_GuardarBachiller(in IdBac varchar(20), in NomBac varchar(20))
begin
	insert into BachillerTb14 (VcBachillerTb14_IdBachiller, VcBachillerTb14_NombreBachiller)
    values (IdBac, NomBac);
end $
call sisae.PaBachillerTb14_GuardarBachiller('11', 'Duodecimo');

/* Buscar Bachiller */
delimiter $
create procedure PaBachillerTb14_BuscarBachiller(in IdBac varchar(20))
begin
	select * from BachillerTb14
     where VcBachillerTb14_IdBachiller = IdBac;
end $
/*call sisae.PaBachillerTb14_BuscarBachiller('11');*/

/* Actualizar Bachiller */
delimiter $
create procedure PaBachillerTb14_ActualizarBachiller(in IdBac varchar(20), in NomBac varchar(20))
begin
	update BachillerTb14
    set   bachillertb14.VcBachillerTb14_NombreBachiller = NomBac
    where   bachillertb14.VcBachillerTb14_IdBachiller = IdBac;
end $
/*call sisae.PaBachillerTb14_ActualizarBachiller('11', 'Nacional');*/

/* Listar Bachiller */
delimiter $
CREATE PROCEDURE PaBachillerTb14_Listar()
begin
	select * from BachillerTb14
	order by bachillertb14.VcBachillerTb14_IdBachiller;
end $
/*call sisae.PaBachillerTb14_Listar();*/

/* Eliminar Bachiller */
delimiter $
create procedure PaBachillerTb14_EliminarBachiller(in IdBac varchar(20))
begin
	delete from BachillerTb14 where bachillertb14.VcBachillerTb14_IdBachiller = IdBac;
end $
/*call sisae.PaBachillerTb14_EliminarBachiller('11');*/


/**************************************************************************************************************************************************************/
	/* EspecialidadTb16 */
/* Guardar Especialidad */
delimiter $
create procedure PaEspecialidadTb16_GuardarEspecialidad(in IdEsp varchar(20), in NomEsp varchar(20), in Cupo int)
begin
	insert into EspecialidadTb16 (VcEspecialidadTb16_IdEspecialidad, VcEspecialidadTb16_Nombre, InEspecialidadTb16_Cupo)
    values (IdEsp, NomEsp, Cupo);
end $
call sisae.PaEspecialidadTb16_GuardarEspecialidad('E01', 'Informatica', 30);

/* Buscar Especialidad */
delimiter $
create procedure PaEspecialidadTb16_BuscarEspecialidad(in IdEsp varchar(20))
begin
	select * from EspecialidadTb16
     where VcEspecialidadTb16_IdEspecialidad = IdEsp;
end $
/*call sisae.PaEspecialidadTb16_BuscarEspecialidad('E01');*/

/* Actualizar Especialidad */
delimiter $
create procedure PaEspecialidadTb16_ActualizarEspecialidad(in IdEsp varchar(20), in NomEsp varchar(20), in Cupo int)
begin
	update EspecialidadTb16
    set   especialidadtb16.VcEspecialidadTb16_Nombre = NomEsp, especialidadtb16.InEspecialidadTb16_Cupo = Cupo
    where especialidadtb16.VcEspecialidadTb16_IdEspecialidad = IdEsp;
end $
/*call sisae.PaEspecialidadTb16_ActualizarEspecialidad('E01', 'Administracion', '20');*/

/* Listar Especialidad */
delimiter $
CREATE PROCEDURE PaEspecialidadTb16_Listar()
begin
	select * from especialidadtb16
	order by especialidadtb16.VcEspecialidadTb16_IdEspecialidad;
end $
/*call sisae.PaEspecialidadTb16_Listar();*/

/* Eliminar Especialidad */
delimiter $
create procedure PaEspecialidadTb16_EliminarEspecialidad(in IdEs varchar(20))
begin
	delete from EspecialidadTb16 where especialidadtb16.VcEspecialidadTb16_IdEspecialidad = IdEs;
end $
/*call sisae.PaEspecialidadTb16_EliminarEspecialidad('E01');*/

/**************************************************************************************************************************************************************/
	/* MateriaTb17 */
/* Guardar Materia */
delimiter $
create procedure PaMateriaTb17_GuardarMateria(in IdMat varchar(20), in NomMat varchar(20))
begin
	insert into MateriaTb17 (VcMateriaTb17_IdMateria, VcMateriaTb17_Nombre)
    values (IdMat, NomMat);
end $
call sisae.PaMateriaTb17_GuardarMateria('M01', 'Matematicas');

/* Buscar Materia */
delimiter $
create procedure PaMateriaTb17_BuscarMateria(in IdMat varchar(20))
begin
	select * from MateriaTb17
     where VcMateriaTb17_IdMateria = IdMat;
end $
/*call sisae.PaMateriaTb17_BuscarMateria('M01');*/

/* Actualizar Materia */
delimiter $
create procedure PaMateriaTb17_ActualizarMateria(in IdMat varchar(20), in NomMat varchar(20))
begin
	update MateriaTb17
    set   materiatb17.VcMateriaTb17_Nombre = NomMat
    where materiatb17.VcMateriaTb17_IdMateria = IdMat;
end $
/*call sisae.PaMateriaTb17_ActualizarMateria('M01', 'Ciencias');*/

/* Listar Materia */
delimiter $
CREATE PROCEDURE PaMateriaTb17_Listar()
begin
	select * from MateriaTb17
	order by materiatb17.VcMateriaTb17_IdMateria;
end $
/*call sisae.PaMateriaTb17_Listar();*/

/* Eliminar Materia */
delimiter $
create procedure PaMateriaTb17_EliminarMateria(in IdMat varchar(20))
begin
	delete from MateriaTb17 where materiatb17.VcMateriaTb17_IdMateria = IdMat;
end $
/*call sisae.PaMateriaTb17_EliminarMateria('M01');*/

/**************************************************************************************************************************************************************/
	/* AsistClaseTb18 */
/* Guardar Asistencia Clase */
delimiter $
create procedure PaAsistClaseTb18_GuardarAsistClase(in IdAsist varchar(20), in Fec date, in Hora time, in Estado varchar(20), in IdMa varchar(20))
begin
	insert into AsistClaseTb18 (VcAsistClaseTb18_IdAsistClase, DtAsistClaseTb18_Fecha, TmAsistClaseTb18_Hora, VcAsistClaseTb18_Estado, VcMateriaTb17_IdMateria)
    values (IdAsist, Fec, Hora, Estado, IdMa);
end $
call sisae.PaAsistClaseTb18_GuardarAsistClase('AC03', '2017/07/05', '8:00', 'Presente', 'M01');

/* Buscar Asistencia Clase */
delimiter $
create procedure PaAsistClaseTb18_BuscarAsistClase(in IdAsis varchar(20))
begin
	select * from AsistClaseTb18
     where asistclasetb18.VcAsistClaseTb18_IdAsistClase = IdAsis;
end $
/*call sisae.PaAsistClaseTb18_BuscarAsistClase('AC03');*/

/* Actualizar Asistencia Clase */
delimiter $
create procedure PaAsistClaseTb18_ActualizarAsistClase(in IdAsist varchar(20), in Fec date, 
in Hora time, in Estado varchar(20), in IdMa varchar(20))
begin
	update AsistClaseTb18
    set   asistclasetb18.DtAsistClaseTb18_Fecha = Fec, asistclasetb18.TmAsistClaseTb18_Hora = Hora, 
    asistclasetb18.VcAsistClaseTb18_Estado = Estado, asistclasetb18.VcMateriaTb17_IdMateria = IdMa
    where asistclasetb18.VcAsistClaseTb18_IdAsistClase = IdAsist;
end $
/*call sisae.PaAsistClaseTb18_ActualizarAsistClase('AC02', '2017/12/09', '12:00', 'Tardia', 'M01');*/

/* Listar Asistencia Clase */
delimiter $
CREATE PROCEDURE PaAsistClaseTb18_Listar()
begin
	select * from AsistClaseTb18
	order by asistclasetb18.VcAsistClaseTb18_IdAsistClase;
end $
/*call sisae.PaAsistClaseTb18_Listar();*/

/* Eliminar Asistencia Clase */
delimiter $
create procedure PaAsistClaseTb18_EliminarAsistClase(in IdAsi varchar(20))
begin
	delete from AsistClaseTb18 where asistclasetb18.VcAsistClaseTb18_IdAsistClase = IdAsi;
end $
/*call sisae.PaAsistClaseTb18_EliminarAsistClase('AC01');*/

/**************************************************************************************************************************************************************/
	/* SeccionTb20 */
/* Guardar Seccion */
delimiter $
create procedure PaSeccionTb20_GuardarSeccion(in IdSec varchar(20), in Cupo varchar(20))
begin
	insert into SeccionTb20 (VcSeccionTb20_IdSeccion, InSeccionTb20_Cupo)
    values (IdSec, Cupo);
end $
call sisae.PaSeccionTb20_GuardarSeccion('7-1', '15');

/* Buscar Seccion */
delimiter $
create procedure PaSeccionTb20_BuscarSeccion(in IdSec varchar(20))
begin
	select * from SeccionTb20
     where SeccionTb20.VcSeccionTb20_IdSeccion = IdSec;
end $
/*call sisae.PaSeccionTb20_BuscarSeccion('7-1');*/

/* Actualizar Seccion */
delimiter $
create procedure PaSeccionTb20_ActualizarSeccion(in IdSec varchar(20), in Cupo varchar(20))
begin
	update SeccionTb20
    set   secciontb20.InSeccionTb20_Cupo = Cupo
    where SeccionTb20.VcSeccionTb20_IdSeccion = IdSec;
end $
/*call sisae.PaSeccionTb20_ActualizarSeccion('7-1', '10');*/

/* Listar Seccion */
delimiter $
CREATE PROCEDURE PaSeccionTb20_Listar()
begin
	select * from SeccionTb20
	order by SeccionTb20.VcSeccionTb20_IdSeccion;
end $
/*call sisae.PaSeccionTb20_Listar();*/

/* Eliminar Seccion */
delimiter $
create procedure PaSeccionTb20_EliminarSeccion(in IdSec varchar(20))
begin
	delete from SeccionTb20  where SeccionTb20.VcSeccionTb20_IdSeccion = IdSec;
end $
/*call sisae.PaSeccionTb20_EliminarSeccion('7-1');*/
